- hosts: dev
  become: yes
  tasks:
    - name: Download dev
      fetch:
        src: ~/github/tmp/
        dest: /home/ubuntu/db/
        flat: yes

    - name: export mysqldump
      mysql_db:
         login_host: "localhost"
         login_user: "hpols_dbuser"
         login_password: "70pH(sXCgYMXiqVM"
         login_port: "3306"
         name: "hpbrtest"
         targent: "/home/ubuntu/db/hpbrtest2021.sql.zip"
         state: "dump"
      